name: Deploy News Aggregator API
concurrency: production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /var/www/turan/news/api
            cd /var/www/turan/news/api

            # Pull latest code
            # If repo not cloned yet, clone it
            if [ ! -d ".git" ]; then
              mkdir -p ~/.ssh
              ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
              git clone git@github.com:okhsat/news-api.git .
            else
              git fetch --all
              git reset --hard origin/master
              git clean -fd
            fi

            # Create .env
            cat > .env <<EOL
            APP_NAME="News Aggregator API"
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_URL=https://api.news.turandevelop.com

            DB_CONNECTION=pgsql
            DB_HOST=${{ vars.DB_HOST }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

            REDIS_HOST=${{ vars.REDIS_HOST }}
            REDIS_PORT=${{ vars.REDIS_PORT }}
            REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"

            QUEUE_CONNECTION=redis
            CACHE_STORE=redis

            NEWSAPI_KEY=${{ secrets.NEWSAPI_KEY }}
            GUARDIAN_KEY=${{ secrets.GUARDIAN_KEY }}
            EOL

            # Install dependencies and optimize
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Ensure required folders exist
            mkdir -p storage bootstrap/cache

            # Fix permissions
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Restart PHP-FPM
            sudo systemctl restart php8.4-fpm
